<?php
/**
 * SellersV2StatsApi
 * PHP version 5
 *
 * @category Class
 * @package  Criteo\Marketing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Marketing API v.1.0
 *
 * IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.
 *
 * The version of the OpenAPI document: v.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Criteo\Marketing\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Criteo\Marketing\ApiException;
use Criteo\Marketing\Configuration;
use Criteo\Marketing\HeaderSelector;
use Criteo\Marketing\ObjectSerializer;

/**
 * SellersV2StatsApi Class Doc Comment
 *
 * @category Class
 * @package  Criteo\Marketing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SellersV2StatsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation campaigns
     *
     * Get stats by campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \Criteo\Marketing\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function campaigns($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $campaign_id = null, $count = null)
    {
        list($response) = $this->campaignsWithHttpInfo($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $campaign_id, $count);
        return $response;
    }

    /**
     * Operation campaignsWithHttpInfo
     *
     * Get stats by campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \Criteo\Marketing\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function campaignsWithHttpInfo($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $campaign_id = null, $count = null)
    {
        $request = $this->campaignsRequest($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $campaign_id, $count);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation campaignsAsync
     *
     * Get stats by campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function campaignsAsync($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $campaign_id = null, $count = null)
    {
        return $this->campaignsAsyncWithHttpInfo($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $campaign_id, $count)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation campaignsAsyncWithHttpInfo
     *
     * Get stats by campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function campaignsAsyncWithHttpInfo($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $campaign_id = null, $count = null)
    {
        $returnType = 'string';
        $request = $this->campaignsRequest($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $campaign_id, $count);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'campaigns'
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function campaignsRequest($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $campaign_id = null, $count = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling campaigns'
            );
        }

        $resourcePath = '/v2/crp/stats/campaigns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($interval_size !== null) {
            $queryParams['intervalSize'] = ObjectSerializer::toQueryValue($interval_size);
        }
        // query params
        if ($click_attribution_policy !== null) {
            $queryParams['clickAttributionPolicy'] = ObjectSerializer::toQueryValue($click_attribution_policy);
        }
        // query params
        if ($start_date !== null) {
            $queryParams['startDate'] = ObjectSerializer::toQueryValue($start_date);
        }
        // query params
        if ($end_date !== null) {
            $queryParams['endDate'] = ObjectSerializer::toQueryValue($end_date);
        }
        // query params
        if ($campaign_id !== null) {
            $queryParams['campaignId'] = ObjectSerializer::toQueryValue($campaign_id);
        }
        // query params
        if ($count !== null) {
            $queryParams['count'] = ObjectSerializer::toQueryValue($count);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sellerCampaigns
     *
     * Get stats by seller-campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \Criteo\Marketing\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function sellerCampaigns($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $campaign_id = null, $count = null)
    {
        list($response) = $this->sellerCampaignsWithHttpInfo($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $campaign_id, $count);
        return $response;
    }

    /**
     * Operation sellerCampaignsWithHttpInfo
     *
     * Get stats by seller-campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \Criteo\Marketing\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function sellerCampaignsWithHttpInfo($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $campaign_id = null, $count = null)
    {
        $request = $this->sellerCampaignsRequest($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $campaign_id, $count);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sellerCampaignsAsync
     *
     * Get stats by seller-campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sellerCampaignsAsync($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $campaign_id = null, $count = null)
    {
        return $this->sellerCampaignsAsyncWithHttpInfo($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $campaign_id, $count)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sellerCampaignsAsyncWithHttpInfo
     *
     * Get stats by seller-campaign.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sellerCampaignsAsyncWithHttpInfo($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $campaign_id = null, $count = null)
    {
        $returnType = 'string';
        $request = $this->sellerCampaignsRequest($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $campaign_id, $count);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sellerCampaigns'
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  string $campaign_id Show only metrics for this campaign (default all campaigns) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sellerCampaignsRequest($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $campaign_id = null, $count = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling sellerCampaigns'
            );
        }

        $resourcePath = '/v2/crp/stats/seller-campaigns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($interval_size !== null) {
            $queryParams['intervalSize'] = ObjectSerializer::toQueryValue($interval_size);
        }
        // query params
        if ($click_attribution_policy !== null) {
            $queryParams['clickAttributionPolicy'] = ObjectSerializer::toQueryValue($click_attribution_policy);
        }
        // query params
        if ($start_date !== null) {
            $queryParams['startDate'] = ObjectSerializer::toQueryValue($start_date);
        }
        // query params
        if ($end_date !== null) {
            $queryParams['endDate'] = ObjectSerializer::toQueryValue($end_date);
        }
        // query params
        if ($seller_id !== null) {
            $queryParams['sellerId'] = ObjectSerializer::toQueryValue($seller_id);
        }
        // query params
        if ($campaign_id !== null) {
            $queryParams['campaignId'] = ObjectSerializer::toQueryValue($campaign_id);
        }
        // query params
        if ($count !== null) {
            $queryParams['count'] = ObjectSerializer::toQueryValue($count);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sellers
     *
     * Get stats by seller.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \Criteo\Marketing\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function sellers($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $count = null)
    {
        list($response) = $this->sellersWithHttpInfo($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $count);
        return $response;
    }

    /**
     * Operation sellersWithHttpInfo
     *
     * Get stats by seller.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \Criteo\Marketing\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function sellersWithHttpInfo($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $count = null)
    {
        $request = $this->sellersRequest($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $count);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sellersAsync
     *
     * Get stats by seller.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sellersAsync($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $count = null)
    {
        return $this->sellersAsyncWithHttpInfo($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $count)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sellersAsyncWithHttpInfo
     *
     * Get stats by seller.
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sellersAsyncWithHttpInfo($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $count = null)
    {
        $returnType = 'string';
        $request = $this->sellersRequest($authorization, $interval_size, $click_attribution_policy, $start_date, $end_date, $seller_id, $count);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sellers'
     *
     * @param  string $authorization JWT Bearer Token (required)
     * @param  string $interval_size Specify the aggregation interval for events used to compute stats (default is \&quot;day\&quot;) (optional)
     * @param  string $click_attribution_policy Specify the click attribution policy for salesUnits, revenue, CR, CPO, COS, and ROAS (optional)
     * @param  \DateTime $start_date Filter out all events that occur before date (default is the value of &#x60;endDate&#x60;) (optional)
     * @param  \DateTime $end_date Filter out all events that occur after date (default is today’s date) (optional)
     * @param  string $seller_id Show only metrics for this seller (default all sellers) (optional)
     * @param  int $count Return up to the first count rows of data (default is all rows) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sellersRequest($authorization, $interval_size = null, $click_attribution_policy = null, $start_date = null, $end_date = null, $seller_id = null, $count = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling sellers'
            );
        }

        $resourcePath = '/v2/crp/stats/sellers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($interval_size !== null) {
            $queryParams['intervalSize'] = ObjectSerializer::toQueryValue($interval_size);
        }
        // query params
        if ($click_attribution_policy !== null) {
            $queryParams['clickAttributionPolicy'] = ObjectSerializer::toQueryValue($click_attribution_policy);
        }
        // query params
        if ($start_date !== null) {
            $queryParams['startDate'] = ObjectSerializer::toQueryValue($start_date);
        }
        // query params
        if ($end_date !== null) {
            $queryParams['endDate'] = ObjectSerializer::toQueryValue($end_date);
        }
        // query params
        if ($seller_id !== null) {
            $queryParams['sellerId'] = ObjectSerializer::toQueryValue($seller_id);
        }
        // query params
        if ($count !== null) {
            $queryParams['count'] = ObjectSerializer::toQueryValue($count);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
