<?php
/**
 * AdvertiserQuotaMessage
 *
 * PHP version 5
 *
 * @category Class
 * @package  Criteo\Marketing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Marketing API v.1.0
 *
 * IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.
 *
 * The version of the OpenAPI document: v.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Criteo\Marketing\Model;

use \ArrayAccess;
use \Criteo\Marketing\ObjectSerializer;

/**
 * AdvertiserQuotaMessage Class Doc Comment
 *
 * @category Class
 * @package  Criteo\Marketing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdvertiserQuotaMessage implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AdvertiserQuotaMessage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'advertiser_id' => 'int',
        'quota_used' => 'int',
        'quota_limit' => 'int',
        'quota_start_date' => '\DateTime',
        'quota_end_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'advertiser_id' => 'int32',
        'quota_used' => 'int32',
        'quota_limit' => 'int32',
        'quota_start_date' => 'date-time',
        'quota_end_date' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'advertiser_id' => 'advertiserId',
        'quota_used' => 'quotaUsed',
        'quota_limit' => 'quotaLimit',
        'quota_start_date' => 'quotaStartDate',
        'quota_end_date' => 'quotaEndDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'advertiser_id' => 'setAdvertiserId',
        'quota_used' => 'setQuotaUsed',
        'quota_limit' => 'setQuotaLimit',
        'quota_start_date' => 'setQuotaStartDate',
        'quota_end_date' => 'setQuotaEndDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'advertiser_id' => 'getAdvertiserId',
        'quota_used' => 'getQuotaUsed',
        'quota_limit' => 'getQuotaLimit',
        'quota_start_date' => 'getQuotaStartDate',
        'quota_end_date' => 'getQuotaEndDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['advertiser_id'] = isset($data['advertiser_id']) ? $data['advertiser_id'] : null;
        $this->container['quota_used'] = isset($data['quota_used']) ? $data['quota_used'] : null;
        $this->container['quota_limit'] = isset($data['quota_limit']) ? $data['quota_limit'] : null;
        $this->container['quota_start_date'] = isset($data['quota_start_date']) ? $data['quota_start_date'] : null;
        $this->container['quota_end_date'] = isset($data['quota_end_date']) ? $data['quota_end_date'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets advertiser_id
     *
     * @return int|null
     */
    public function getAdvertiserId()
    {
        return $this->container['advertiser_id'];
    }

    /**
     * Sets advertiser_id
     *
     * @param int|null $advertiser_id advertiser_id
     *
     * @return $this
     */
    public function setAdvertiserId($advertiser_id)
    {
        $this->container['advertiser_id'] = $advertiser_id;

        return $this;
    }

    /**
     * Gets quota_used
     *
     * @return int|null
     */
    public function getQuotaUsed()
    {
        return $this->container['quota_used'];
    }

    /**
     * Sets quota_used
     *
     * @param int|null $quota_used quota_used
     *
     * @return $this
     */
    public function setQuotaUsed($quota_used)
    {
        $this->container['quota_used'] = $quota_used;

        return $this;
    }

    /**
     * Gets quota_limit
     *
     * @return int|null
     */
    public function getQuotaLimit()
    {
        return $this->container['quota_limit'];
    }

    /**
     * Sets quota_limit
     *
     * @param int|null $quota_limit quota_limit
     *
     * @return $this
     */
    public function setQuotaLimit($quota_limit)
    {
        $this->container['quota_limit'] = $quota_limit;

        return $this;
    }

    /**
     * Gets quota_start_date
     *
     * @return \DateTime|null
     */
    public function getQuotaStartDate()
    {
        return $this->container['quota_start_date'];
    }

    /**
     * Sets quota_start_date
     *
     * @param \DateTime|null $quota_start_date quota_start_date
     *
     * @return $this
     */
    public function setQuotaStartDate($quota_start_date)
    {
        $this->container['quota_start_date'] = $quota_start_date;

        return $this;
    }

    /**
     * Gets quota_end_date
     *
     * @return \DateTime|null
     */
    public function getQuotaEndDate()
    {
        return $this->container['quota_end_date'];
    }

    /**
     * Sets quota_end_date
     *
     * @param \DateTime|null $quota_end_date quota_end_date
     *
     * @return $this
     */
    public function setQuotaEndDate($quota_end_date)
    {
        $this->container['quota_end_date'] = $quota_end_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


